name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - run: npm i
      # - run: npm run build
      # - run: npm run test

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/html/
          remote_host: 15.206.49.180
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
      
      - name: Node Js
        uses: actions/setup-node@v1
        
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master        
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh      
            sudo npm i
            sudo npm run build
            sudo npm start
            service myservice restart
      
      # - name: Build & Deploy
      #   env:
      #       PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #       HOSTNAME: ${{secrets.HOST_NAME}}
      #       USER_NAME: ${{secrets.USER_NAME}}
      
      #   run: |
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

      #         # Now we have got the access of EC2 and we will start the deploy .
      #         export NVM_DIR=~/.nvm
      #         source ~/.nvm/nvm.sh

      #         cd /var/www/html &&
      #         sudo npm i &&
      #         sudo npm run build &&
      #         sudo npm start
      #         '
